name: Copy file to remote server

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy file to remote server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i ~/.ssh/id_rsa -o BatchMode=yes -o StrictHostKeyChecking=no eugenechua@52.74.36.87 "echo SSH connection successful"

