name: Copy file to remote server

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
    - name: Copy file using SCP with password
      run: sshpass -p !20240221eugeneIGS scp -o StrictHostKeyChecking=no -P 22 package.json eugenechua@52.74.36.87:/home/eugenechua/
