name: Fill Environment Secrets to .env

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: 'eugenechua'
        password: '!20240221eugeneIGS'
        port: 22
        source: "."
        target: "/home/eugenechua"
