name: Fill Environment Secrets to .env

on:
  push:
    branches: [ dotenv ]

jobs:
  fill_secrets:
    runs-on: self-hosted
    environment: test  # This should match your environment name on GitHub    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Environment Secrets to .env
        run: |
          echo "MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" > .env
          echo "GAMETOWER_PRIVATE_KEY=${{ secrets.GAMETOWER_PRIVATE_KEY }}" >> .env
          # Add more secrets if needed
          
      - name: Show .env file
        run: cat .env

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: eugenechua
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ".env"
          target: "/home/eugenechua"
          