name: Copy file to remote server

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy file to remote server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "Directory created"
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        echo "Private key written"
        chmod 600 ~/.ssh/id_rsa
        echo "Permissions set"
        ssh-keyscan -H 52.74.36.87 >> ~/.ssh/known_hosts
        echo "Host key scanned"

