name: Fill Environment Secrets to .env

on:
  push:
    branches:
      - main

jobs:
  fill_secrets:
    runs-on: ubuntu-latest
    environment: test  # This should match your environment name on GitHub    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Environment Secrets to .env
        run: |
          echo "MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}" > .env
          echo "GAMETOWER_PRIVATE_KEY=${{ secrets.GAMETOWER_PRIVATE_KEY }}" >> .env
          # Add more secrets if needed
          
      - name: Show .env file
        run: cat .env

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: eugenechua
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCTD5TscXmT4gO8uv1RI1yFkkOJH9mwIHcxSTanTodRKKbjZyGhPFK9jXipQADXkUjS3UtpZ4+0wYYbmAG6tX3WU3RU6WvEXe5AlSI4Ei4oG//0TI8z1ISxKVi7m+HGskhPkGKLXrtAzIuPNnJERd8KYk8of6nVCzC7G+jCOw1RUTlIYCmmBAUHn2IuYb0eH8d+qtWdyVms9b1sKa3HBgCe9AXxy6z78vHvBUMM/vmFOX7Znu9LmJJ7z/FCVSblXXFNQ6JCiGuEdQGFQ11Es14MvZ8c3O2UduSPB69QYVjGwvRvaS4iZXMo0gn3HM9ZhUnXlWFjf+gm7g12uFpOQiqx eugenechua@master
          port: 22
          source: ".env"
          target: "/home/eugenechua"
          