name: Copy file to remote server

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy file to remote server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        if [ -z "${SSH_PRIVATE_KEY}" ]; then
          echo "SSH_PRIVATE_KEY is not set"
          exit 1
        else
          echo "SSH_PRIVATE_KEY is set"
        fi
