name: Fill Environment Secrets to .env

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: 52.74.36.87
        username: "eugenechua"
        password: "!20240221eugeneIGS"
        local-dir: "."        